### ISSUE TITLE
Update to nestjs 6.0.0

### ISSUE THREAD

**Issue by maricn** [nest-cloud/schedule#13]
`npm WARN nest-schedule@0.4.5 requires a peer of @nestjs/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`

Please update to the newest version of nestjs. Thank you

**Comment by miaowing** [comment]
Please upgrade to 0.1.1, thks

**Comment by maricn** [comment]
Thanks. I was a bit confused with the change in the package distribution as well.

**Comment by danil-z** [comment]
Didn't get the solution?
the latest release of this library is 0.4.6...
I'm getting this:

`npm WARN nest-schedule@0.4.5 requires a peer of @nestjs/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by maricn** [comment]
> Didn't get the solution?
> the latest release of this library is 0.4.6...
> I'm getting this:
> 
> `npm WARN nest-schedule@0.4.5 requires a peer of @nestjs/common@^5.0.0 but none is installed. You must install peer dependencies yourself.`

They changed the distribution at https://github.com/miaowing/nest-schedule/commit/143f61e7c9c09260249a277b83c4129731ccd05b#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R2 but it seems it was reverted back to `nest-schedule` with version `0.4.6` two days ago. Anyways, `0.4.6` still retains the changes in dependencies, so should be good to use.

**Comment by maricn** [comment]
Although, a bit of transparency with the package name and licensing would be appreciated. @miaowing

**Comment by miaowing** [comment]
I'm so sorry. This package is one of [nestcloud](https://github.com/nest-cloud/nestcloud)'s components, You can use '@nestcloud/schedule' and also you can use the standalone version 'nest-schedule' too. If you not use nestcloud, I recommend you to use nest-schedule, Thanks. @maricn

**Comment by miaowing** [comment]
Now, this two packages will be maintenance standalone in two repositories:

https://github.com/miaowing/nest-schedule

https://github.com/nest-cloud/nestcloud/tree/master/packages/schedule

**Comment by kuriel-trivu** [comment]
nest-schedule@0.6.4 requires a peer of @nestjs/core@^6.1.1

    "@nestjs/core": "7.6.5",
    "nest-schedule": "0.6.4",
    
Module stoped to work.
